version: "3"
services:
  container:
    image: ${DOCKER_IMAGE:-ubuntu}
    container_name: ${CONTAINER_NAME:-container}
    working_dir: ${CONTAINER_PATH:-/app}
    command: tail -f /dev/null
    user: root
    environment:
      CONTAINER_PATH: ${CONTAINER_PATH:-/app}
    volumes:
      - .:${CONTAINER_PATH:-/app}
